export const TYPE_MONGODB_DEFAULT_CONNECTION = 'DEFAULT';
export const TYPE_MONGODB_MODULE_OPTIONS = 'TYPE_MONGODB_MODULE_OPTIONS';
export const TYPE_MONGODB_MODULE_ID = 'TYPE_MONGODB_MODULE_ID';
export const TYPE_MONGODB_DOCUMENT_MANAGER = 'TYPE_MONGODB_DOCUMENT_MANAGER';
export const TYPE_MONGODB_DOCUMENT_MANAGERS = 'TYPE_MONGODB_DOCUMENT_MANAGERS';
